CREATE DATABASE PIZZAHUT

USE PIZZAHUT

SELECT * FROM ORDER_DETAILS
SELECT * FROM ORDERS
SELECT * FROM PIZZA_TYPES
SELECT * FROM PIZZAS

ALTER TABLE PIZZAS
ALTER COLUMN PRICE FLOAT


ALTER TABLE ORDER_DETAILS
ALTER COLUMN QUANTITY INT

SELECT COUNT(*) AS TOTAL_ORDER_PLACED
FROM ORDERS

WITH TEMP AS (
SELECT OD.*, P.PRICE
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON P.PIZZA_ID =OD.PIZZA_ID
)
SELECT ROUND(SUM(PRICE * QUANTITY),2) AS TOTAL_REV_PIZZAS
FROM TEMP

SELECT * FROM PIZZAS
WHERE PRICE = (SELECT MAX(PRICE) FROM PIZZAS)

SELECT TOP 1 PT.NAME,P.PRICE
FROM PIZZAS P
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID =PT.PIZZA_TYPE_ID
ORDER BY P.PRICE DESC


SELECT TOP 1 P.SIZE, COUNT(OD.ORDER_DETAILS_ID) AS COMMOM_ORDER
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY P.SIZE
ORDER BY COUNT(OD.ORDER_DETAILS_ID) DESC


SELECT TOP 5 P.PIZZA_TYPE_ID,PT.NAME, SUM(QUANTITY) AS TOTAL_QTY
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON OD.PIZZA_ID = P.PIZZA_ID
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY P.PIZZA_TYPE_ID,PT.NAME
ORDER BY SUM(QUANTITY) DESC

SELECT DATEPART(HOUR,TIME) AS HOURS, COUNT(ORDER_ID) AS FREQ_ORDERS FROM ORDERS
GROUP BY DATEPART(HOUR,TIME)
ORDER BY COUNT(ORDER_ID) DESC

SELECT CATEGORY, COUNT(NAME)
FROM PIZZA_TYPES
GROUP BY CATEGORY

WITH CTE AS(
SELECT O.DATE, SUM(OD.QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS O
JOIN ORDER_DETAILS OD
ON O.ORDER_ID =OD.ORDER_ID
GROUP BY O.DATE
)
SELECT AVG(TOTAL_QUANTITY) AS AVG_ORDER_PER_DAY FROM CTE


select TOP 3 P.PIZZA_TYPE_ID,PT.NAME, SUM(QUANTITY*P.PRICE) AS REVENUE
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON OD.PIZZA_ID = P.PIZZA_ID
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY P.PIZZA_TYPE_ID,PT.NAME
ORDER BY REVENUE DESC




WITH CTE AS (

SELECT SUM(OD.QUANTITY * P.PRICE) AS TOTAL_REV 
FROM ORDER_DETAILS OD 
JOIN PIZZAS P
ON OD.PIZZA_ID=P.PIZZA_ID
)

select PT.CATEGORY, (ROUND(SUM(QUANTITY*P.PRICE),0)/(SELECT TOTAL_REV FROM CTE)*100) AS REVENUE_PERCENTAGE
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON OD.PIZZA_ID = P.PIZZA_ID
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.CATEGORY
ORDER BY SUM(QUANTITY*P.PRICE)  DESC




WITH CTE AS (

SELECT MONTH(O.DATE) AS MONTH,ROUND(SUM(OD.QUANTITY * P.PRICE),0) AS TOTAL_REV 
FROM ORDER_DETAILS OD 
JOIN PIZZAS P
ON OD.PIZZA_ID=P.PIZZA_ID
JOIN ORDERS O
ON O.ORDER_ID =OD.ORDER_ID
GROUP BY MONTH(O.DATE)
)

SELECT *, SUM(TOTAL_REV) OVER(ORDER BY MONTH) AS RUNNING_TOTAL_REV
FROM CTE



WITH TEMP AS (

select PT.CATEGORY, PT.PIZZA_TYPE_ID,PT.NAME, ROUND(SUM(QUANTITY*P.PRICE),0) AS REVENUE
FROM ORDER_DETAILS OD
JOIN PIZZAS P
ON OD.PIZZA_ID = P.PIZZA_ID
JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.PIZZA_TYPE_ID,PT.NAME,PT.CATEGORY

)
SELECT * FROM (
SELECT CATEGORY,PIZZA_TYPE_ID,NAME, ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS Rn
FROM TEMP) AS RN1
WHERE RN <=3
